# Generated by Django 3.2 on 2022-01-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_reservation_booking_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='listings.bookinginfo'),
        ),
    ]
