# Generated by Django 3.2 on 2022-01-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_reservation_booking_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
