# Generated by Django 3.2 on 2022-02-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20220128_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfo',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='isBooked',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='booking_info',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='isBooked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='listings.hotelroom'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel_room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='listings.hotelroomtype'),
        ),
    ]
