# Generated by Django 3.2 on 2022-02-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20220207_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='listings.hotelroom'),
        ),
    ]
