# Generated by Django 3.2 on 2022-02-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_bookinginfo_hotel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='hotel_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='listings.hotelroom'),
        ),
    ]
