# Generated by Django 3.2 on 2022-02-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20220207_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfo',
            name='hotel_room',
        ),
    ]
